# GitHub Ruleset Configuration for Main Branch Protection
# 🚀 Configure in GitHub: Settings > Rules > Rulesets > New branch ruleset

# === BASIC CONFIGURATION ===
ruleset_name: "Main Branch Protection - Satellite Image API"
enforcement_status: "Active"  # Active | Evaluate | Disabled
target_branches: "~DEFAULT_BRANCH"  # Targets main/master branch automatically

# === BRANCH RULES TO ENABLE ===

# ✅ CRITICAL PROTECTIONS
restrict_deletions: true           # ✅ Only allow users with bypass permission to delete
block_force_pushes: true          # ✅ Prevent force pushes
require_pull_request: true        # ✅ Require PRs before merging

# ✅ PULL REQUEST REQUIREMENTS
pr_settings:
  required_approving_review_count: 1
  dismiss_stale_reviews_on_push: true
  require_code_owner_review: false
  require_last_push_approval: false        # Set to true for extra security
  required_review_thread_resolution: true

# ✅ STATUS CHECKS (CRITICAL FOR CI)
require_status_checks: true
status_checks_must_be_up_to_date: true    # Require branches to be current
required_status_checks:
  - "code-quality"    # Matches workflow job name
  - "security"        # Matches workflow job name
  - "test"           # Matches workflow job name

# ✅ COMMIT QUALITY
require_linear_history: true              # Prevent messy merge commits
commit_message_pattern: |
  ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([a-z0-9-]+\\))?(!)?: .{1,100}
  # Enforces conventional commits: feat: add new feature

# ⚠️  OPTIONAL RULES (Enable as needed)
require_signed_commits: false             # Enable for high-security projects
require_deployments_to_succeed: false     # Enable if using GitHub deployments
require_code_scanning: false              # Enable for advanced security scanning

# === BYPASS LIST ===
# Organization/Repository admins can bypass by default
# Add specific users/teams/apps if needed in the GitHub UI

# === 🔧 SETUP INSTRUCTIONS ===
# 1. Go to: Repository Settings → Rules → Rulesets
# 2. Click: "New branch ruleset"
# 3. Copy settings from this file:
#    - Name: "Main Branch Protection - Satellite Image API"
#    - Target: "Default branch"
#    - Enforcement: "Active"
# 4. Enable Branch Rules:
#    ☑️ Restrict deletions
#    ☑️ Block force pushes
#    ☑️ Require linear history
#    ☑️ Require a pull request before merging (1 approval, dismiss stale reviews)
#    ☑️ Require status checks to pass (code-quality, security, test)
# 5. Optional: Add conventional commit pattern
# 6. Save ruleset

# === 📋 VERIFICATION CHECKLIST ===
# After setup, verify:
# ☑️ Direct pushes to main are blocked
# ☑️ PRs require 1 approval
# ☑️ All 3 status checks must pass
# ☑️ Branches must be up-to-date before merge
# ☑️ Force pushes are blocked
# ☑️ Branch deletions are blocked
