# GitHub Ruleset Configuration for main branch
# Configure these in GitHub: Settings > Rules > Rulesets > New branch ruleset
# This file documents the required ruleset settings (GitHub Rulesets replace classic branch protection)

ruleset_name: "Main Branch Protection"
target_branches:
  - "main"
enforcement: active  # Options: active, evaluate, disabled

# === PULL REQUEST REQUIREMENTS ===
pull_request_rules:
  required: true
  required_approving_review_count: 1
  dismiss_stale_reviews: true
  require_code_owner_reviews: false
  require_last_push_approval: false
  required_review_thread_resolution: true

# === STATUS CHECK REQUIREMENTS ===
status_check_rules:
  required: true
  strict_required_status_checks_policy: true  # Require branches to be up to date
  required_status_checks:
    - context: "code-quality"
      integration_id: null  # GitHub Actions
    - context: "security" 
      integration_id: null  # GitHub Actions
    - context: "test"
      integration_id: null  # GitHub Actions

# === BRANCH RESTRICTIONS ===
branch_restrictions:
  restrict_deletions: true
  restrict_force_pushes: true
  restrict_pushes: true  # Require pull requests
  required_linear_history: true

# === ADDITIONAL RULES ===
additional_rules:
  require_signed_commits: false
  require_deployments_to_succeed: false
  
# === BYPASS PERMISSIONS ===
# Only repository admins can bypass these rules by default
# Configure specific users/teams in the GitHub UI if needed
bypass_actors: []  # Configure in UI: Settings > Rules > Rulesets > [Ruleset] > Bypass list

# === SETUP INSTRUCTIONS ===
# 1. Go to GitHub repository Settings
# 2. Navigate to Rules > Rulesets  
# 3. Click "New branch ruleset"
# 4. Configure settings above
# 5. Set target to "main" branch
# 6. Set enforcement to "Active"
# 7. Enable required status checks: code-quality, security, test
